# Generated by Django 5.1.6 on 2026-09-16 13:49

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.core.validators.ImageFileValidator()], verbose_name='image')),
                ('image_alt', models.CharField(blank=True, max_length=160, verbose_name='image alt text')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('show_in_nav', models.BooleanField(default=True, verbose_name='show in navigation')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured on homepage')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(blank=True, help_text='One line shown on product cards.', max_length=300, verbose_name='short description')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('highlights', models.TextField(blank=True, help_text="One selling point per line, e.g. 'Grass-fed, no antibiotics'.", verbose_name='highlights')),
                ('storage_instructions', models.CharField(blank=True, help_text="Shown on perishable items, e.g. 'Keep refrigerated at 2-4 C'.", max_length=220, verbose_name='storage instructions')),
                ('farm_note', models.CharField(blank=True, help_text="Provenance line, e.g. 'From our Savar dairy unit'.", max_length=220, verbose_name='farm note')),
                ('is_perishable', models.BooleanField(default=True, help_text='Perishable products require an expiry date on every stock batch.', verbose_name='perishable')),
                ('default_shelf_life_days', models.PositiveIntegerField(default=7, help_text='Used to pre-fill the expiry date when receiving new stock.', verbose_name='default shelf life (days)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='featured')),
                ('published_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Leave empty to keep the product out of the storefront.', null=True, verbose_name='published at')),
                ('rating_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='average rating')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='review count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-is_featured', '-published_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()], verbose_name='image')),
                ('alt_text', models.CharField(help_text='Describe the image for screen readers and search engines.', max_length=160, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ('-is_primary', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text="Shown to shoppers, e.g. '1 Litre bottle'.", max_length=120, verbose_name='variant name')),
                ('sku', models.CharField(help_text='Stock keeping unit. Used on batches, orders and packing slips.', max_length=40, unique=True, verbose_name='SKU')),
                ('pack_size', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='pack size')),
                ('unit', models.CharField(choices=[('litre', 'Litre'), ('ml', 'Millilitre'), ('kg', 'Kilogram'), ('g', 'Gram'), ('pc', 'Piece'), ('dozen', 'Dozen'), ('pack', 'Pack')], default='pc', max_length=10, verbose_name='unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price, shown struck through. Leave empty when not discounted.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='compare-at price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Internal only. Powers the margin column in sales analytics.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cost price')),
                ('weight_grams', models.PositiveIntegerField(default=0, help_text='Shipping weight. 0 when delivery is not weight-priced.', verbose_name='weight (grams)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ('sort_order', 'price'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='products_ca_is_acti_5dffbf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'published_at'], name='products_pr_is_acti_002d50_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating_average'], name='products_pr_rating__754437_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active', 'price'], name='products_pr_is_acti_7bbea7_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', Decimal('0.00'))), name='variant_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gte', models.F('price')), _connector='OR'), name='compare_price_not_below_price'),
        ),
    ]
