# Generated by Django 5.1.6 on 2026-09-16 13:49

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=220, verbose_name='description')),
                ('districts', models.TextField(blank=True, help_text='Comma separated, e.g. Dhaka, Gazipur. Matched case-insensitively.', verbose_name='districts')),
                ('areas', models.TextField(blank=True, help_text='Comma separated, e.g. Dhanmondi, Gulshan. Checked before districts.', verbose_name='areas / thanas')),
                ('postcodes', models.TextField(blank=True, help_text='Comma separated. Checked first when present.', verbose_name='postcodes')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='delivery fee')),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the site-wide threshold. Set 0 to never ship free.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='free delivery threshold')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='minimum order amount')),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=1, verbose_name='earliest delivery (days)')),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=2, verbose_name='latest delivery (days)')),
                ('cod_available', models.BooleanField(default=True, verbose_name='cash on delivery available')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, help_text='Used when no other zone matches the address.', verbose_name='fallback zone')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'delivery zone',
                'verbose_name_plural': 'delivery zones',
                'ordering': ('sort_order', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='only_one_default_delivery_zone')],
            },
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label', models.CharField(help_text='e.g. Morning (8 AM - 11 AM)', max_length=80, verbose_name='label')),
                ('start_time', models.TimeField(verbose_name='window opens')),
                ('end_time', models.TimeField(verbose_name='window closes')),
                ('cutoff_hours', models.PositiveSmallIntegerField(default=4, help_text='Orders must be placed this many hours before the window opens.', verbose_name='cutoff (hours before)')),
                ('max_orders_per_day', models.PositiveIntegerField(default=0, help_text='0 means unlimited.', verbose_name='capacity per day')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('zone', models.ForeignKey(blank=True, help_text='Leave empty to offer this slot in every zone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='delivery.deliveryzone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'delivery slot',
                'verbose_name_plural': 'delivery slots',
                'ordering': ('sort_order', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_bd_phone], verbose_name='phone')),
                ('vehicle', models.CharField(choices=[('bike', 'Motorbike'), ('van', 'Van'), ('cycle', 'Bicycle'), ('truck', 'Refrigerated truck')], default='bike', max_length=10, verbose_name='vehicle')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('notes', models.CharField(blank=True, max_length=220, verbose_name='notes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_profile', to=settings.AUTH_USER_MODEL, verbose_name='linked staff account')),
                ('zones', models.ManyToManyField(blank=True, related_name='partners', to='delivery.deliveryzone', verbose_name='zones covered')),
            ],
            options={
                'verbose_name': 'delivery partner',
                'verbose_name_plural': 'delivery partners',
                'ordering': ('name',),
            },
        ),
    ]
