# Generated by Django 5.1.6 on 2026-09-16 13:49

import apps.core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('coupons', '0001_initial'),
        ('delivery', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Order placed'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('packed', 'Packed'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20, verbose_name='order status')),
                ('payment_status', models.CharField(choices=[('pending', 'Awaiting payment'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Tracked separately from the fulfilment status.', max_length=20, verbose_name='payment status')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on delivery'), ('mock', 'Sandbox checkout'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('sslcommerz', 'Card or bank (SSLCommerz)')], default='cod', max_length=20, verbose_name='payment method')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('ship_recipient', models.CharField(max_length=150, verbose_name='recipient')),
                ('ship_phone', models.CharField(max_length=20, verbose_name='delivery phone')),
                ('ship_alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='alternate phone')),
                ('ship_division', models.CharField(max_length=40, verbose_name='division')),
                ('ship_district', models.CharField(max_length=80, verbose_name='district')),
                ('ship_area', models.CharField(max_length=120, verbose_name='area')),
                ('ship_address_line', models.CharField(max_length=255, verbose_name='street address')),
                ('ship_postcode', models.CharField(blank=True, max_length=10, verbose_name='postcode')),
                ('ship_note', models.CharField(blank=True, max_length=200, verbose_name='delivery note')),
                ('requested_delivery_date', models.DateField(blank=True, null=True, verbose_name='requested delivery date')),
                ('tracking_note', models.CharField(blank=True, max_length=200, verbose_name='tracking note')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='delivery fee')),
                ('delivery_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='delivery discount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount paid')),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount refunded')),
                ('coupon_code', models.CharField(blank=True, max_length=32, verbose_name='coupon code')),
                ('customer_note', models.TextField(blank=True, max_length=500, verbose_name='customer note')),
                ('staff_note', models.TextField(blank=True, verbose_name='internal note')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='cancellation reason')),
                ('access_token', models.CharField(default=apps.core.utils.random_token, editable=False, help_text='Unguessable id used in emailed tracking links.', max_length=48, verbose_name='access token')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('placed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='placed at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('packed_at', models.DateTimeField(blank=True, null=True, verbose_name='packed at')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='dispatched at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address', verbose_name='saved address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon', verbose_name='coupon')),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliverypartner', verbose_name='rider')),
                ('delivery_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryslot', verbose_name='delivery slot')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryzone', verbose_name='delivery zone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('-placed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Order placed'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('packed', 'Packed'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=20, verbose_name='status')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('is_customer_visible', models.BooleanField(default=True, verbose_name='visible to customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order event',
                'verbose_name_plural': 'order events',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product_name', models.CharField(max_length=200, verbose_name='product')),
                ('variant_name', models.CharField(max_length=120, verbose_name='variant')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='SKU')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='unit price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='line total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-placed_at'], name='orders_orde_user_id_2e20df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-placed_at'], name='orders_orde_status_ab153f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-placed_at'], name='orders_orde_payment_18b19e_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', Decimal('0.00'))), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', Decimal('0.00'))), name='order_amount_paid_non_negative'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_4c5f76_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.00'))), name='order_item_price_non_negative'),
        ),
    ]
