# Generated by Django 5.1.6 on 2026-09-16 13:49

import apps.accounts.managers
import apps.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=10, verbose_name='label')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='recipient name')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_bd_phone], verbose_name='phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_bd_phone], verbose_name='alternate phone')),
                ('division', models.CharField(choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], default='dhaka', max_length=20, verbose_name='division')),
                ('district', models.CharField(max_length=80, verbose_name='district')),
                ('area', models.CharField(max_length=120, verbose_name='area / thana')),
                ('address_line', models.CharField(help_text='House, road, block and any building name.', max_length=255, verbose_name='street address')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='postcode')),
                ('delivery_note', models.CharField(blank=True, help_text='Landmark or instructions for the rider.', max_length=200, verbose_name='delivery note')),
                ('is_default', models.BooleanField(default=False, verbose_name='default address')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone', models.CharField(blank=True, help_text='Used for delivery coordination and order updates.', max_length=20, null=True, unique=True, validators=[apps.core.validators.validate_bd_phone], verbose_name='mobile number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the farm dashboard.', verbose_name='staff status')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('marketing_opt_in', models.BooleanField(default=False, help_text='Consent to receive offers and seasonal produce updates.', verbose_name='marketing emails')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
