# Generated by Django 5.1.6 on 2026-09-16 13:49

import apps.core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('eyebrow', models.CharField(blank=True, max_length=60, verbose_name='eyebrow')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('subtitle', models.TextField(blank=True, max_length=400, verbose_name='subtitle')),
                ('image', models.ImageField(help_text='Large farm photography. 2400x1400px or wider works best.', upload_to='homepage/hero/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()], verbose_name='image')),
                ('image_alt', models.CharField(help_text='Describe the photo for screen readers.', max_length=160, verbose_name='image alt text')),
                ('cta_label', models.CharField(blank=True, max_length=40, verbose_name='button label')),
                ('cta_url', models.CharField(blank=True, max_length=300, verbose_name='button link')),
                ('secondary_cta_label', models.CharField(blank=True, max_length=40, verbose_name='secondary button label')),
                ('secondary_cta_url', models.CharField(blank=True, max_length=300, verbose_name='secondary button link')),
            ],
            options={
                'verbose_name': 'hero slide',
                'verbose_name_plural': 'hero slides',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('title', models.CharField(max_length=140, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='summary')),
                ('body', models.TextField(help_text='Supports basic HTML. Rendered inside a styled prose container.', verbose_name='body')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='show in footer')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('placement', models.CharField(choices=[('home_mid', 'Homepage - middle'), ('home_bottom', 'Homepage - bottom'), ('shop_top', 'Shop - top')], default='home_mid', max_length=20, verbose_name='placement')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name='subtitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/banners/%Y/%m/', validators=[apps.core.validators.ImageFileValidator()], verbose_name='image')),
                ('image_alt', models.CharField(blank=True, max_length=160, verbose_name='image alt text')),
                ('cta_label', models.CharField(blank=True, max_length=40, verbose_name='button label')),
                ('cta_url', models.CharField(blank=True, max_length=300, verbose_name='button link')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
            ],
            options={
                'verbose_name': 'promo banner',
                'verbose_name_plural': 'promo banners',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('brand_name', models.CharField(default='XaninFarm', max_length=80, verbose_name='brand name')),
                ('tagline', models.CharField(default='Fresh From Our Farm, Delivered to Your Door.', max_length=160, verbose_name='tagline')),
                ('about_short', models.TextField(blank=True, help_text='One paragraph shown in the footer and about strip.', verbose_name='short about text')),
                ('announcement_text', models.CharField(blank=True, max_length=180, verbose_name='announcement text')),
                ('announcement_url', models.CharField(blank=True, max_length=300, verbose_name='announcement link')),
                ('announcement_active', models.BooleanField(default=False, verbose_name='show announcement')),
                ('support_phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_bd_phone], verbose_name='support phone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_bd_phone], verbose_name='WhatsApp number')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='support email')),
                ('farm_address', models.CharField(blank=True, max_length=255, verbose_name='farm address')),
                ('opening_hours', models.CharField(blank=True, default='Sat-Thu, 8:00 AM - 8:00 PM', max_length=120, verbose_name='opening hours')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='default delivery fee')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text='Orders at or above this subtotal ship free. Set 0 to disable.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='free delivery threshold')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='minimum order amount')),
                ('cod_enabled', models.BooleanField(default=True, verbose_name='cash on delivery enabled')),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('author_name', models.CharField(max_length=80, verbose_name='author name')),
                ('author_location', models.CharField(blank=True, max_length=80, verbose_name='author location')),
                ('quote', models.TextField(max_length=400, verbose_name='quote')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/', validators=[apps.core.validators.ImageFileValidator()], verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('icon', models.CharField(choices=[('leaf', 'Leaf'), ('truck', 'Delivery truck'), ('shield', 'Shield'), ('clock', 'Clock'), ('heart', 'Heart'), ('cow', 'Cow')], default='leaf', max_length=20, verbose_name='icon')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('description', models.CharField(max_length=220, verbose_name='description')),
            ],
            options={
                'verbose_name': 'value proposition',
                'verbose_name_plural': 'value propositions',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
