# Generated by Django 5.1.6 on 2026-09-16 13:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Stored uppercase. Customers type this at checkout.', max_length=32, unique=True, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off'), ('free_delivery', 'Free delivery')], default='percent', max_length=16, verbose_name='discount type')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent for percentage coupons, taka for fixed. Ignored for free delivery.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Caps percentage coupons. Leave empty for no cap.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='maximum discount')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='minimum order amount')),
                ('applies_to', models.CharField(choices=[('all', 'Everything'), ('categories', 'Selected categories'), ('products', 'Selected products')], default='all', max_length=16, verbose_name='applies to')),
                ('usage_limit_total', models.PositiveIntegerField(default=0, help_text='0 means unlimited.', verbose_name='total usage limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='0 means unlimited.', verbose_name='per-customer limit')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, verbose_name='times used')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='new customers only')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='starts at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='products.category', verbose_name='categories')),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='products.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount amount')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon', verbose_name='coupon')),
            ],
            options={
                'verbose_name': 'coupon redemption',
                'verbose_name_plural': 'coupon redemptions',
                'ordering': ('-created_at',),
            },
        ),
    ]
