# Generated by Django 5.1.6 on 2026-09-16 13:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0.00'))), name='coupon_value_non_negative'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'user'], name='coupons_cou_coupon__5ef611_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_redemption_per_order'),
        ),
    ]
