# Generated by Django 5.1.6 on 2026-09-16 13:49

import apps.payments.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(choices=[('cod', 'Cash on delivery'), ('mock', 'Sandbox checkout'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('sslcommerz', 'Card or bank (SSLCommerz)')], db_index=True, max_length=20, verbose_name='provider')),
                ('reference', models.CharField(default=apps.payments.models.generate_reference, editable=False, help_text='Merchant reference sent to the gateway.', max_length=40, unique=True, verbose_name='our reference')),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text="The gateway's transaction id.", max_length=120, verbose_name='provider reference')),
                ('instrument_hint', models.CharField(blank=True, help_text="Masked description only, e.g. 'bKash 01XXXXXX789'.", max_length=60, verbose_name='instrument')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='BDT', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='failure reason')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='provider response')),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='initiated at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='order')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Set for cash collected by a rider or entered by staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('provider_reference', models.CharField(blank=True, max_length=120, verbose_name='provider reference')),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='provider response')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_refunds', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(db_index=True, max_length=20, verbose_name='provider')),
                ('event_id', models.CharField(help_text="The provider's own id for this notification.", max_length=160, verbose_name='event id')),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=20, verbose_name='kind')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='signature verified')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='received', max_length=12, verbose_name='status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='error')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='source IP')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='refund_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'status', '-created_at'], name='payments_we_provide_d353dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_webhook_event_per_provider'),
        ),
    ]
