# Generated by Django 5.1.6 on 2026-09-16 13:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('batch_number', models.CharField(help_text='Supplier or farm batch reference, e.g. MILK-2026-09-12-A.', max_length=60, verbose_name='batch number')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='production date')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='received date')),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Required for perishable products. Expired stock is never sold.', null=True, verbose_name='expiry date')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='quantity received')),
                ('quantity_available', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='quantity available')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='quantity reserved')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='unit cost')),
                ('supplier', models.CharField(blank=True, max_length=140, verbose_name='supplier / farm unit')),
                ('storage_location', models.CharField(blank=True, help_text='Cold room, rack, crate...', max_length=80, verbose_name='storage location')),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantine', 'Quarantine'), ('expired', 'Expired'), ('depleted', 'Depleted'), ('recalled', 'Recalled')], default='active', max_length=12, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'inventory batch',
                'verbose_name_plural': 'inventory batches',
                'ordering': ('expiry_date', 'received_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('movement_type', models.CharField(choices=[('receive', 'Stock received'), ('reserve', 'Reserved for order'), ('release', 'Reservation released'), ('ship', 'Shipped to customer'), ('return', 'Returned to stock'), ('adjust', 'Manual adjustment'), ('expire', 'Written off - expired'), ('recall', 'Written off - recalled')], max_length=10, verbose_name='type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantity')),
                ('available_delta', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='available change')),
                ('reserved_delta', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='reserved change')),
                ('balance_available', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='available after')),
                ('balance_reserved', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='reserved after')),
                ('reference_type', models.CharField(blank=True, help_text='order, adjustment, task...', max_length=30, verbose_name='reference type')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='reference id')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventorybatch', verbose_name='batch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantity')),
                ('status', models.CharField(choices=[('held', 'Held'), ('consumed', 'Consumed'), ('released', 'Released')], db_index=True, default='held', max_length=10, verbose_name='status')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Unpaid orders release their hold after this time.', null=True, verbose_name='hold expires at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventorybatch', verbose_name='batch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.order', verbose_name='order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.orderitem', verbose_name='order item')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'stock reservation',
                'verbose_name_plural': 'stock reservations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['variant', 'status', 'expiry_date'], name='inventory_i_variant_ba5b87_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['status', 'quantity_available'], name='inventory_i_status_ab1912_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('variant', 'batch_number'), name='unique_batch_number_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='batch_available_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='batch_reserved_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='batch_received_not_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant', '-created_at'], name='inventory_s_variant_608d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order', 'status'], name='inventory_s_order_i_9b314c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['status', 'expires_at'], name='inventory_s_status_c656ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_quantity_positive'),
        ),
    ]
