# Generated by Django 5.1.6 on 2026-09-16 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('orders_placed', models.PositiveIntegerField(default=0, verbose_name='orders placed')),
                ('orders_delivered', models.PositiveIntegerField(default=0, verbose_name='orders delivered')),
                ('orders_cancelled', models.PositiveIntegerField(default=0, verbose_name='orders cancelled')),
                ('orders_returned', models.PositiveIntegerField(default=0, verbose_name='orders returned')),
                ('items_sold', models.PositiveIntegerField(default=0, verbose_name='items sold')),
                ('new_customers', models.PositiveIntegerField(default=0, verbose_name='new customers')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total of every order placed on this date.', max_digits=12, verbose_name='gross revenue')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross revenue less cancelled and returned orders.', max_digits=12, verbose_name='net revenue')),
                ('discount_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount given')),
                ('delivery_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='delivery fees')),
                ('refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='refunded')),
                ('cod_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Placed on this date and not yet paid for.', max_digits=12, verbose_name='cash to collect')),
            ],
            options={
                'verbose_name': 'daily sales snapshot',
                'verbose_name_plural': 'daily sales snapshots',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['-date'], name='analytics_d_date_bd48b7_idx')],
            },
        ),
    ]
