# Generated by Django 5.1.6 on 2026-09-16 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 'Excellent'), (4, 'Very good'), (3, 'Average'), (2, 'Poor'), (1, 'Terrible')], verbose_name='rating')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='headline')),
                ('body', models.TextField(max_length=2000, verbose_name='review')),
                ('status', models.CharField(choices=[('pending', 'Awaiting moderation'), ('approved', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='verified purchase')),
                ('staff_reply', models.TextField(blank=True, max_length=1000, verbose_name='reply from the farm')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
                ('order_item', models.ForeignKey(blank=True, help_text='The delivered line this review is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.orderitem', verbose_name='purchased line')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='product')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='replied by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'status', '-created_at'], name='reviews_rev_product_17c7c8_idx'), models.Index(fields=['status', '-created_at'], name='reviews_rev_status_70a1f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='one_review_per_product_per_customer'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
    ]
